### ISSUE TITLE
Breaking out of scopes

### ISSUE THREAD

**Issue by guybedford** [domenic/package-name-maps#13]
The scope concept is looking really great, but this line worries me a little:

> Notice also how the full URL path of the nested lodash package was composed: roughly, top "path_prefix" + scope name + scope's "path_prefix" + package's "path". This design minimizes repetition.

Repetition is not a bad thing if it helps clarify understanding. Web developers are going to spend a lot of their lives banging their heads against this manifest when it isn't working, we should aim to remember that.

Specifically, if I wanted a scope to redirect to an entirely different location, say even another server, that doesn't seem possible with the current composition rules given the above.

I'd like to suggest we open up the path_prefix for scopes to be a base-level relative URL, just like the top-level path_prefix. Allowing the repetition brings both predictability and more flexibility.

**Comment by domenic** [comment]
It's possible; just use absolute URLs or URLs prefixed with a `/` instead of relative ones.

**Comment by guybedford** [comment]
Right, the wording above made this sound like a concatenation not a successive URL resolution.

So the rule then would be `resolve(path_prefix + scope_name, scope_path_prefix + package_path)`?

**Comment by domenic** [comment]
Hmm, I don't want to commit to that exactly until we've actually written out the algorithm (#6), but I'll say that that's the intent at least... We're doing some tricky things with auto-inserting `/` suffixes (because it's really error-prone to require them) that make me unsure where exactly we do resolve and where we do concatenation and where we insert /s.

**Comment by guybedford** [comment]
Right, it's with this logic that a lot of my concerns in https://github.com/domenic/package-name-maps/issues/11 stem from as well, so it may be better to discuss there.

The initial issue posted isn't a problem though it sounds like after all, thanks for clarifying.
