### ISSUE TITLE
What about <script type="module" src="moment">?

### ISSUE THREAD

**Issue by vitalets** [domenic/package-name-maps#24]
Will package map be used for script tags with bare src?
```html
<script type="module" src="moment"></script>
```

**Comment by ljharb** [comment]
This is very compelling.

**Comment by domenic** [comment]
No; that already means something (namely resolving the relative URL `moment` against the page's base URL.)

See #23 for possible ways to allow usage of bare identifiers in other contexts; IMO the leading contender would be `src="package:moment"`.
