### ISSUE TITLE
Optimize module instances

### ISSUE THREAD

**Issue by arcanis** [domenic/package-name-maps#28]
Consider the following case:

  - We have a package `foo`
  - `foo` depends on `bar`, `baz`, and `qux@1`
  - Both `bar` and `baz` depend on `qux@2`

In this situation, the tree that npm and Yarn will currently generate looks like this:

```
/node_modules/Foo/node_modules/Qux
/node_modules/Bar/node_modules/Qux
/node_modules/Qux
```

They cannot hoist the `qux` you see in `foo` and `bar`, because it would then conflict with the version requested by `foo`. As such, it needs to be duplicated on the disk, even though it's the exact same files. Because of this, Node will also duplicate them in memory (there will be two instances of `qux@1`), and I think the same thing will happen here according to this specification.

Given that this situation actually happens in real life and that the hoisting is a purely optional mechanism (a package manager could choose to completely disable the hoisting, for example), I think it would be nice to design a way to say that a file should be instantiated a single time for each time it can be found in the tree (there's a catch: peer dependencies, but I'll come to that later).

**Comment by domenic** [comment]
It's unclear what part of your issue is related to package name maps. This seems to be a feature request for yarn/npm, as far as I can tell. Or maybe for the module system to do some kind of content-hash based deduping? If the latter, I can tell you that is not feasible, and we'll be sticking with URL-based module maps.

**Comment by arcanis** [comment]
It's not exactly about package name maps itself, but rather what the resolver will do with the data it contains (it's more about the semantic it exposes than its format).

I guess my comment can be reformulated like this: *what does it means if two resolutions from different scopes resolve to the same file path*? I see three possible options:

  - It means that the loader will be required to instanciate them a single time
  - It means that the loader will be required to instanciate them once for each file
  - No requirement is made, in which case it will be implementation-defined

The third option seems a bit dangerous. The second one is wasteful but matches what currently happens in Node-land. The first one is more optimized, but has issues regarding peer dependencies.

Hope it makes more sense

**Comment by domenic** [comment]
The loader always operates on a URL basis. The package name maps are about translating bare specifiers into URLs. Scopes just govern how in some places `"bare-specifier"` can map to one URL, and in some places it can map to another URL.

Does that help?

**Comment by arcanis** [comment]
It helps, thanks! 🙂

I was wondering if there wasn't a way to alter this behavior from within the package name maps (for example by specifying something like a "version" field that would tell the loader that two identical paths with the same version should share the same instance while two identical paths with different versions would be duplicated in memory), but I don't think it's really needed for my use case, and it would make the whole thing quite more complex.

**Comment by matthewp** [comment]
@arcanis I think tooling that generates packagemaps can do that sort of decision making.

**Comment by arcanis** [comment]
It's not (only) about the tooling; there's just no way to have a single path and two instances with the current system. The only way is to have two different paths, which means that the same file will be fetched twice from the server.

**Comment by matthewp** [comment]
What is the reason to have a single path with two instances?

**Comment by matthewp** [comment]
I think you could do this with query params.

**Comment by arcanis** [comment]
Packages that have peer dependencies effectively are "multiple packages in one": they share the same code, but not the same dependencies (since those are provided by their ancestors, and two ancestors might give them different versions). Because of this, they need to be instanced once for each set of dependency they have.

It's a bit of a fringe case (peer dependencies are usually only provided by the top-level package, so no conflict occurs) so it's not a big deal if there's no way to prevent fetching the same files multiple times, but it's still something to keep in mind.

> I think you could do this with query params.

iirc, two urls with the same path but different query params are treated as separate resources and their caches aren't shared, so it would duplicate the package in memory, but would also still require a round trip to the server for each of them.

The specs makes it hard to specify query params, since most resolved paths will be derived (for example if you have `import "lodash/isFunction.js"` in your code, you can't have the package name maps add any query params right now, because the `/isFunction.js` part is derived from the require path. You'd need to manually use `import "lodash/isFunction.js?foo"`, which isn't great).
