### ISSUE TITLE
URLs and scope names

### ISSUE THREAD

**Issue by arcanis** [domenic/package-name-maps#29]
I spotted the following line in the proposal:

> Notice also how the full URL path of the nested lodash package was composed: roughly, top `path_prefix` + scope name + scope's `path_prefix + package's `path`. This design minimizes repetition.

Let's say I have the following package-name-maps:

```json
{
  "path_prefix": "https://foo.bar",
  "packages": {
    "A": { "path": "A@1", "main": "index.js" },
    "B": { "path": "B@1", "main": "index.js" }
  },
  "scopes": {
    "A": {
      "packages": {
        "C": { "path": "C@1", "main": "index.js" }
      }
    },
    "B": {
      "packages": {
        "C": { "path": "C@2", "main": "index.js" }
      }
    }
  }
}
```

According to the line I quoted, it means that:

- Resolving `A` from the toplevel will call `https://foo.bar/A@1/index.js`
- Resolving `B` from the toplevel will call `https://foo.bar/B@1/index.js`
- Resolving `C` from `A` will call `https://foo.bar/A/C@1/index.js`
- Resolving `C` from `B` will call `https://foo.bar/B/C@2/index.js`

I feel like the first two resolutions make sense, but the two others don't. Is automatically adding the scope name to the URL (with no way to prevent this short of maybe using `../` as `path_prefix`, which is unintuitive and whose behavior isn't clearly defined) a good idea?

Since this file will end up being automatically generated in most cases, it seems a bit premature to optimize for less repetition.

**Comment by justinfagnani** [comment]
Since a scope defines a path and is a prefix of the refererURL, it makes sense to me that paths within a scope are relative to the path of the scope.

As you point out, you can refer outside of the scope path by using `../`:

```json
{
  "path_prefix": "https://foo.bar",
  "packages": {
    "A": { "path": "A@1", "main": "index.js" },
    "B": { "path": "B@1", "main": "index.js" }
  },
  "scopes": {
    "A": {
      "packages": {
        "C": { "path": "../C@1", "main": "index.js" }
      }
    },
    "B": {
      "packages": {
        "C": { "path": "../C@2", "main": "index.js" }
      }
    }
  }
}
```

**Comment by arcanis** [comment]
I find it really confusing, especially considering that this rule behavior is ambiguous in itself. The scope names are not strictly correlated to the filesystem paths, so why make the scopes package paths relative to the scope names rather than the scopes paths? ie has a user, I could expect the following:

```
https://foo.bar/A@1/C@2/index.js
https://foo.bar/B@1/C@2/index.js
```

But definitely not

```
https://foo.bar/A/C@2/index.js
https://foo.bar/B/C@2/index.js
```

I can guess that the main argument for this behavior is that it's much simpler to just use the scope name rather than the package paths, but my point is that automatically composing path is a confusing behavior in itself, which counterbalances the "less repetition" argument. I'd prefer things to be explicit rather than implicit and subject to varying expectations.

**Comment by justinfagnani** [comment]
Scopes are independent from packages and don't have names - they are very explicitly and only paths. The reason is the role of a scope: it's used to look up a map based on the refererURL.

**Comment by arcanis** [comment]
Does that make my example above wrong, and should be this instead: ?

```
{
  ...,
  "scopes": {
    "A@1": {
       ...,
    },
    "B@1": {
       ...,
    }
  }
}
```

**Comment by justinfagnani** [comment]
Ah, yes. Though we should be careful to be clear with statements like "Resolving C from A". The "from" part really should be a path to be most clear.

**Comment by arcanis** [comment]
I see - if the scopes keys are URLs/paths, then I think the relative behavior semantically makes much more sense, thanks!

**Comment by justinfagnani** [comment]
cc @domenic for the discussion. Emphasizing that scopes are path-keyed and never referring to "scope name" would probably be helpful.

**Comment by guybedford** [comment]
This tripped me up too and seems like a common catch from the way the examples are described.

**Comment by domenic** [comment]
I am on vacation through April 1, but would be happy to review PRs clarifying this or other aspects in the meantime.
