### ISSUE TITLE
Sub modules relying on package.json resolution within sub folder

### ISSUE THREAD

**Issue by ggoodman** [domenic/package-name-maps#34]
### Context

I've recently built a tool [cdn-run](https://github.com/ggoodman/cdn-run) designed to help solve this problem in a very specific context: a browser-based code editor (see: [next.plnkr.co](https://next.plnkr.co/edit)). This tool will take a set of top-level dependencies and a package metadata resolver function and will generate a `SystemJS` configuration suitable for executing code in the context of the requested set of dependencies.

### Roadblock

In testing this approach, I came across `@angular/core/http` in Angular that relies on npm module resolution semantics via deep `package.json`. This means that creating the static `SystemJS` configuration for this module is impossible without peeking into its contents. Given the similar objects of package name maps, I wonder if this will also be an issue here.

Specifically, consider [`@angular/core`](https://unpkg.com/@angular/common@5.2.9/) and [`@angular/core/http`](https://unpkg.com/@angular/common@5.2.9/http/) (click links to see package contents). While the former can easily be represented in a package name map, how would the latter be represented?

### Problem in the context of package name maps

**What are the semantics for two package specifiers where one is a prefix of the other?** In node, we rely on the module resolution algorithm consulting `package.json` to dereference the intended entry point at each level of the tree, but it is unclear to me how this would work in the proposed spec.

**Comment by justinfagnani** [comment]
I can't tell what's happening with those specific Angular packages, because they don't seem to include any actual source, but this seems to be a dupe of #16.

**Comment by ggoodman** [comment]
@justinfagnani I think that this is indeed a duplicate of #16.

I'm going to close this and ask about the specificity concern over there.
