### ISSUE TITLE
Benefit of path_prefix and separation of path and main

### ISSUE THREAD

**Issue by sokra** [domenic/package-name-maps#35]
I don't see the benefit of:

* `path_prefix` (Maybe for size reasons? Doesn't gzip also eliminate this?)
* Separation of `path` and `main` (Maybe for defaulting `path`?)

And instead propose to omit these things. I also propose to make **scopes a first-class-citizen** which leads to the following format. (Assuming this format will be created by a tool and not by human.)

``` js
{
  "/": { // scope (origin of the request)
    // alias for a module
    "moment": "/node_modules/moment/src/moment.js",
    "lodash": "/node_modules/lodash-es/lodash.js",
    // alias for a inner request
    "lodash/pluck": "/node_modules/lodash-es/lib/pluck.js"
    // alias for all inner requests
    "lodash/*": "/node_modules/lodash-es/lib/*",
    // alias for full urls: i. e. for extensions
    "/my/app/file": "/my/app/file.js"
  },
  "/node_modules/html-to-text": { // scope
    "lodash-es": "/node_modules/html-to-text/node_modules/lodash-es/lodash.js",
    "lodash-es/*": "/node_modules/html-to-text/node_modules/lodash-es/*",
    "lodash": "lodash-es",
    "lodash/*": "lodash-es/*"
  }
}
```

* When looking for an alias, matching scopes are processed from longest to shortest
  * This means the root scope `"/"` is always processed at last
* Order in objects doesn't matter
* alias are matched by specificy. `lodash/*` < `lodash/inner/*` < `lodash/inner/request`
* alias must match exactly except when `/*` is appended.
* When successfully matched the URL is replaced and the aliasing starts again
  * You can use a chain of aliases like with `"lodash": "lodash-es"`
* Technically this proposal doesn't know about "modules". It's just a aliasing for URLs. Which is more browser-like in my opinion.
* It's possible to use extension-less requests like `../app/file` in your application, because aliasing them is supported: `"/my/app/file": "/my/app/file.js"`
* It's easy to merge multiple alias maps, i. e. `npm` generated map with your application custom map.
* It's easy to understand and implement. See following snippet.

A very simple implementing could look like this:

``` js
// Scope: { key, rules }
// Rule: { key, alias }

const scopes = ...;
// scopes ordered by key.length
// rules ordered by specificy

function process(origin, request) {
  for(const scope of scopes) {
    if(origin.startsWith(scope.key)) {
      for(const rule of scope.rules) {
        if(rule.key.endsWith("/*")) {
          if(request.startsWith(rule.key.substring(0, rule.key.length - 2))) {
            return process(origin, rule.alias + request.substring(rule.key.length - 2));
          }
        } else {
          if(request === rule.key) {
            return process(origin, rule.alias);
          }
        }
      }
    }
  }
  return request;
}
```

A real implementation could be more efficient. A real implementation should also prevent circular aliasing and throw instead.

---

Possible concerns compared to the original proposal:

* It's more noisy
  * True, I'm assuming this format is written by tooling and compressed via gzip
* It's no longer human-editable
  * True, when using `node_modules` the number of modules is huge anyway, so you really want to use a tool for this.
  * A human-editable format could be transpiled to this format.
  * It's human-editable for small applications which don't use `node_modules`.
  * A tool-generated file could be merged with a application-specific custom file

---

Possible additions:

#### Load scopes on demand

``` js
{
  "/node_modules/html-to-text": "/node_modules/html-to-text/alias.json"
}
```

Some parts of the alias mapping could be loaded when needed by passing an URL to the alias file as scope. This would reduce the size.

#### Relative URLs

Currently only absolute URLs are used. Relative URLs could resolve to the browser rules relative to the `JSON` file. This would make this alias file location-independent.

---

What do you think about this?

**Comment by bmeck** [comment]
I think that we need to be careful when talking about this being generic URL aliasing. HTML and CSS do not have the leading `./`, `../`, and `/` guard that JS has in their existing resolution algorithms.

**Comment by matthewp** [comment]
`path_prefix` would be helpful when writing packagemaps by hand.

**Comment by justinfagnani** [comment]
> Separation of `path` and `main` (Maybe for defaulting path?)

The reason for this is so you can access modules within a package by package name + path:

```json5
{
  "packages": {
    "three": {"path": "node_modules/three", main: "Three.js"}
  }
}
```

allows you to import both `'three'` and `'three/math/Matrix4.js'`.

**Comment by domenic** [comment]
Since it sounds like both aspects the OP is wondering about have been addressed---thanks @matthewp and @justinfagnani---I'll close this. See also https://github.com/domenic/package-name-maps/issues/20 for why scopes and paths are separate.

Thanks for your interest, @sokra!
