### ISSUE TITLE
Fix the ../../../ importing problem

### ISSUE THREAD

**Issue by jantimon** [domenic/package-name-maps#36]
One cool feature of package-name-maps could be an alias to the current module.

Let's say you would have the following folder structure:

```
└── src
    ├── components
    │   └── atoms
    │       └── date-picker
    └── util
        └── date
```

To import `date` from `button` you have to write a quite unreadable import:

```js
import date from '../../../util/date':
```

However with **package-name-maps** this could be improved a lot!

package.json

```
{
   "name": "fancy-app"
}
```

package-name-map:

```
{
  "path_prefix": "/",
  "packages": {
    "fancy-app": { "path": "." }
  }
}
```

Now the same import in date-picker is easier to read and still works if copied to another file:

```
   import 'fancy-app/src/util/date';
```

**Comment by RangerMauve** [comment]
If `fancy-app` is at the root of your website, you could already use `/src/util/date` since import takes URLs.

**Comment by domenic** [comment]
Yep, as @RangerMauve notes, this is not an issue in the browser.
