### ISSUE TITLE
Repeating history

### ISSUE THREAD

**Issue by GrosSacASac** [domenic/package-name-maps#42]
Ryan dahl regrets that require("name") was not specific enough.

Thoughts ?

https://www.youtube.com/watch?v=M3BM9TB-8yA

**Comment by ljharb** [comment]
His regrets are irrelevant; the ecosystem exists.

**Comment by justinfagnani** [comment]
And package-name-maps solve the specificity issue as well. A name resolved against a map has a single deterministic answer.

I think we can close this.
